server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #配置HA互相注册
      register-with-eureka: false
  #关闭eureka的自我保护功能
  server:
    enable-self-preservation: false

