spring:
  application:
    name: lastwhisper-aoplog
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/logdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
aop:
  log:
    controller: true
    service: true
    dao: true

