spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ggb2312/config-repo
          username: gjgb2312@gmail.com
          password: 15037584397.gg
          basedir: D:\Temp
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"